### ISSUE TITLE
MAC address not saving

### ISSUE THREAD

**Issue by crashtestoz** [toddaustin07/LGTV#1]
Thank you for creating the Edge Driver. I installed it as instructed and I was able to control the TV once connected. However, I can not update the MAC address in the settings, It does save and hence I can not test the TV On functionality.

I am running SmartThings Hub v3 (FW 000.050.00010) and the Smart Things App on IOS 17.1.1 iPhone 14Pro

Hoping its an easy fix.

**Comment by crashtestoz** [comment]
I managed to save the MAC address after a few tries.

**Comment by toddaustin07** [comment]
I'm afraid it was most likely a temporary SmartThings app issue.  I have seen reports of similar problems, which seems to be sporadic, and possibly more common on iOS.

I'll go ahead and close this, but let me know if you have any further problems.
